/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ems_tailoring;

/**
 *
 * @author HP
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MCBTN = new javax.swing.JButton();
        pbtn = new javax.swing.JButton();
        obtn = new javax.swing.JButton();
        tbtn = new javax.swing.JButton();
        mbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbtn1 = new javax.swing.JButton();
        FCBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MCBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MCBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems_tailoring/man.png"))); // NOI18N
        MCBTN.setText("MANAGE MALE CUSTOMERS");
        MCBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCBTNActionPerformed(evt);
            }
        });
        getContentPane().add(MCBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 30, -1, -1));

        pbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems_tailoring/closet.png"))); // NOI18N
        pbtn.setText("MANAGE PRODUCTS");
        pbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbtnActionPerformed(evt);
            }
        });
        getContentPane().add(pbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        obtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        obtn.setIcon(new javax.swing.ImageIcon("D:\\EMS_Tailoring_Images\\received.png")); // NOI18N
        obtn.setText("MANAGE ORDERS");
        obtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtnActionPerformed(evt);
            }
        });
        getContentPane().add(obtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        tbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems_tailoring/tailor.png"))); // NOI18N
        tbtn.setText("TAILORS");
        tbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnActionPerformed(evt);
            }
        });
        getContentPane().add(tbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, -1, -1));

        mbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems_tailoring/measuring.png"))); // NOI18N
        mbtn.setText("MEASUREMENTS");
        mbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnActionPerformed(evt);
            }
        });
        getContentPane().add(mbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO EMS TAILORING!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 768, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cbtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems_tailoring/customer-review.png"))); // NOI18N
        cbtn1.setText("MANAGE CUSTOMERS");
        cbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        FCBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FCBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems_tailoring/woman.png"))); // NOI18N
        FCBTN.setText("MANAGE FEMALE CUSTOMERS");
        FCBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCBTNActionPerformed(evt);
            }
        });
        getContentPane().add(FCBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems_tailoring/Modernize-9741-3 (1) (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MCBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCBTNActionPerformed
        // TODO add your handling code here:
      MCustomer field = new  MCustomer();
      field.setVisible(true);
      setVisible(false);
    }//GEN-LAST:event_MCBTNActionPerformed

    private void pbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbtnActionPerformed
        // TODO add your handling code here:
        Products field = new Products();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pbtnActionPerformed

    private void obtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtnActionPerformed
        // TODO add your handling code here:
        Order1 field = new Order1();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_obtnActionPerformed

    private void mbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnActionPerformed
        // TODO add your handling code here:
        Measurements field = new Measurements();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mbtnActionPerformed

    private void tbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnActionPerformed
        // TODO add your handling code here:
        TailorsInfo field = new TailorsInfo();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tbtnActionPerformed

    private void cbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtn1ActionPerformed
        // TODO add your handling code here:
        Customer field = new Customer();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_cbtn1ActionPerformed

    private void FCBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCBTNActionPerformed
        // TODO add your handling code here:
        FCustomer field = new FCustomer();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_FCBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FCBTN;
    private javax.swing.JButton MCBTN;
    private javax.swing.JButton cbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mbtn;
    private javax.swing.JButton obtn;
    private javax.swing.JButton pbtn;
    private javax.swing.JButton tbtn;
    // End of variables declaration//GEN-END:variables
}
